#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check
  methods: [ POST ]

api_v1:
  prefix: '/api/v1'
  resource: '../src/Controller/Api/V1'
  type: annotation
  name_prefix: 'v1.'

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }